// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmvdkconvipvalumapys.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttdmRrY29udmlwdmFsdW1hcHlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzOTcxMDYsImV4cCI6MjA2MDk3MzEwNn0.5Wh1R_e-cXWL2B9NRgZs7aKQNHkMKMKE5BeDA6cXxFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);